# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1339e48ef3391b373d5597058e22acb03d0a004a6fb33fb987f4d2f414559c9469b3cdfaa63cd1c37d0bca4246a8cfbb593477052c6a0d2609d2e58c58a31842

test:
  secret_key_base: 8ec62ad78f0b6f91084f14585b1bf535a1aff827fe37b2cf9401a5aecf60a55a8b24d50af93e93a37b12dbf85e619f7823a83d2d5156a67d5967d5d978b84f17

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
